#!/bin/bash
curl --location --request POST 'localhost:4000/raft/add' \
--header 'Content-Type: application/json' \
--data-raw '{
        "NodeIdentifier": "node_3",
        "FullAddress": "127.0.0.1:5200"
}'